- name: install hunspell
  package:
    name: hunspell
    state: present

- name: install hunspell language packages
  package:
    name: "hunspell-{{ item }}"
    state: present
  loop: "{{ hunspell_languages }}"
