- name: install designer tools
  package:
    name:
      - gimp
      - blender
    state: present

- name: install drawio
  kewlfft.aur.aur:
    use: yay
    name:
      - drawio-desktop
  become: false
